apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-metabase
  name: app-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-metabase
  template:
    metadata:
      labels:
        app: app-metabase
    spec:
      containers:
      - image: metabase/metabase
        name: metabase
        ports:
        - containerPort: 3000
