apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-metabase
  name: app-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-metabase
  template:
    metadata:
      labels:
        app: app-metabase
    spec:
      containers:
      - image: metabase/metabase
        name: metabase
        ports:
        - containerPort: 3000
      envFrom:
        -configMapRef:
          name: metabase-config 
        -secretRef:
          name: metabase-credentials
      env:
        - name: MB_MAIL
          valueFrom:
            secretKeyRef:
              name: metabase-credentials
              key: MB_MAIL
        - name: MB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metabase-credentials
              key: MB_PASSWORD
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3

