apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  db-name: bWV0YWJhc2VkYg== # metabasedb en base64
  db-password: ZnJhbmNv # franco en base64
  db-username: RnJhbmNvMTIz # Franco123 en base64

