apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db
      labels:
        app: db
        version: v0.1
    spec:
      containers:
        - name: db
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-username
          ports:
            - name: db-mysql
              containerPort: 3306
          volumeMounts:
            - name: sql-volume
              mountPath: "/docker-entrypoint-initdb.d/"
      volumes:
        - name: init-db-script
          configMap:
            name: init-db-script

